version: '2'
services:
  web:
    container_name: web_php
    image: php-docker:dockerfile_php
    build:
      context: ./
    volumes:
      - /Users/norbertogomez/Documents/projects/tests/php/upload_file/:/var/www/html
    ports:
      - 9000:80